name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: C:\\Users\\iray\\AppData\\Local\\Android\Sdk
      JAVA_HOME: C:\\Program Files\\Java\\jdk1.8.0_202
      PATH: C:\\Program Files (x86)\\Android\\android-sdk\\platform-tools:$PATH
    steps:
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: Run adb devices
      run: adb devices

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Appium
      run: npm install -g appium@1.22.3

    - name: Start Appium server
      run: appium &

    - name: Build
      run: dotnet build TestProject3/TestProject3.csproj

    - name: Run NUnit tests
      run: dotnet test TestProject3/TestProject3.csproj --configuration Release

    - name: Test
      run: dotnet test --no-build --verbosity normal
