name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    

   
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        sdk-version: '30'  # Set the desired SDK version
        accept-licenses: true
        platform-tools-version: '31.0.0' 
    - name: Set up Android Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
          api-level: 29
          target: default
          arch: x86
          script: ./gradlew assembleDebug
    - name: Run your Android tests
      run: |
        ./gradlew assembleDebug
        ./gradlew connectedCheck
    - name: Run adb devices
      run: adb devices

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Appium
      run: npm install -g appium@1.22.3

    - name: Start Appium server
      run: appium &

    - name: Build
      run: dotnet build TestProject3/TestProject3.csproj

    - name: Run NUnit tests
      run: dotnet test TestProject3/TestProject3.csproj --configuration Release

    - name: Test
      run: dotnet test --no-build --verbosity normal
